version: 2

models:
  - name: flights

    data_tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 1
      - dbt_expectations.expect_table_column_count_to_equal:
          value: 16

    columns:
      - name: flight_iata_code
        description: "Flight number IATA code"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          - dbt_expectations.expect_column_values_to_be_unique

      - name: country_code
        description: "Code of the country of the flight"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          - dbt_expectations.expect_column_value_lengths_to_equal:
              value: 2

      - name: latitude
        description: "Latitude of the position of the flight"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double
          - dbt_expectations.expect_column_values_to_not_be_null

      - name: longitude
        description: "Longitude of the position of the flight"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double
          - dbt_expectations.expect_column_values_to_not_be_null

      - name: altitude_meters
        description: "Altitude of the flight (in meters)"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint

      - name: speed_horizontal
        description: "Horizontal speed of the flight (in km/h)"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint

      - name: speed_vertical
        description: "Vertical speed of the flight (in km/h)"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint

      - name: squawk_signal_code
        description: "Squawk signal code of the flight"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          - dbt_expectations.expect_column_value_lengths_to_equal:
              value: 4

      - name: flight_status
        description: "Flight status"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ['en-route', 'scheduled', 'landed']
          - dbt_expectations.expect_column_values_to_not_be_null

      - name: airline_iata_code
        description: "Airline IATA code"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          - dbt_expectations.expect_column_values_to_not_be_null

      - name: departure_airport_iata_code
        description: "Departure airport IATA code"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar

      - name: arrival_airport_iata_code
        description: "Arrival airport IATA code"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar

      - name: aircraft_registration_number
        description: "Aircraft registration number"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          - dbt_expectations.expect_column_values_to_not_be_null

      - name: aircraft_type
        description: "Aircraft type"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          - dbt_expectations.expect_column_values_to_not_be_null

      - name: processed_timestamp
        description: "UTC timestamp indicating when the record was processed"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp with time zone
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_row_values_to_have_recent_data:
              datepart: day
              interval: 1

unit_tests:
  - name: test_flights
    description: "Verify the logic of the flights model"
    model: flights
    given:
      - input: source('raw', 'flights')
        rows:
          - {flight_iata: "AR1774", flag: "AR", lat: -25.68102, lng: -54.708376, alt: 1556, speed: 444, v_speed: 2, squawk: null, status: en-route, airline_iata: "AR", dep_iata: "EZE", arr_iata: "IGR", reg_number: "LV-FRQ", type: "adsb", updated: 1723206049}
          - {flight_iata: "AR1774", flag: "DE", lat: -25.68102, lng: -54.708376, alt: 1556, speed: 444, v_speed: 2, squawk: null, status: en-route, airline_iata: "AR", dep_iata: "EZE", arr_iata: "IGR", reg_number: "LV-FRQ", type: "adsb", updated: 1723206048}
          - {flight_iata: "AR1304", flag: "AR", lat: -28.723273, lng: null, alt: 11000, speed: 851, v_speed: 4, squawk: null, status: en-route, airline_iata: "AR", dep_iata: "EZE", arr_iata: "MIA", reg_number: "LV-KAN", type: "adsb", updated: 1723206049}
    expect:
      rows:
          - {flight_iata_code: "AR1774", country_code: "AR", latitude: -25.68102, longitude: -54.708376, altitude_meters: 1556, speed_horizontal: 444, speed_vertical: 2, squawk_signal_code: null, flight_status: en-route, airline_iata_code: "AR", departure_airport_iata_code: "EZE", arrival_airport_iata_code: "IGR", aircraft_registration_number: "LV-FRQ", aircraft_type: "adsb", event_timestamp: "2024-08-09 12:20:49+00:00"}
