name: 'aviation_analytics'
version: '1.0.0'
config-version: 2

profile: 'aviation_analytics'

vars:
  'dbt_date:time_zone': 'UTC'

clean-targets:
  - "target"
  - "dbt_packages"

models:
  aviation_analytics:
    +materialized: table
    curated:
      +schema: curated
    raw:
      +schema: raw
