version: 2

sources:
  - name: airlabs_api_data
    description: Raw datasets ingested from the AirLabs API.
    meta:
      external_location: "data/{name}.json"
    tables:
      - name: routes
        description: Dataset containing routes data.
