version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/dbt"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directories:
      - "/dbt"
      - "/metabase"
    schedule:
      interval: "monthly"

  # docker-compose is not supported by dependabot yet
  # - package-ecosystem: "docker"
  #   directory: "/"
  #   schedule:
  #     interval: "monthly"
