version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/dbt"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "UTC"

  - package-ecosystem: "docker"
    directories:
      - "/dbt"
      - "/metabase"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "UTC"

  # docker-compose is not supported by dependabot yet
  # - package-ecosystem: "docker"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #     day: "monday"
  #     time: "00:00"
  #     timezone: "UTC"
