name: 'aviation_analytics_dbt'
version: '1.0.0'
config-version: 2

profile: 'aviation_analytics_dbt_duckdb'

vars:
  'dbt_date:time_zone': 'UTC'

clean-targets:
  - "target"
  - "dbt_packages"

models:
  aviation_analytics_dbt:
    +materialized: table
