name: 'aviation_analytics_dbt'
version: '1.0.0'
config-version: 2

profile: 'aviation_analytics_dbt_duckdb'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  aviation_analytics_dbt:
    departures:
      +materialized: table
