version: 2

models:
  - name: departures_raw
  - name: departures_curated
    columns:
      - name: airline_iata_code
        description: "IATA code of the airline"
      - name: flight_number_iata_code
        description: "IATA code of the flight"
      - name: departure_airport_iata_code
        description: "IATA code of the origin airport"
      - name: departure_terminals
        description: "Departure terminals"
      - name: departure_time_local
        description: "Departure time (local)"
      - name: departure_time_utc
        description: "Departure time (UTC)"
      - name: arrival_airport_iata_code
        description: "IATA code of the destination airport"
      - name: arrival_terminals
        description: "Arrival terminals"
      - name: arrival_time_local
        description: "Arrival time (local)"
      - name: arrival_time_utc
        description: "Arrival time (UTC)"
      - name: flight_days
        description: "Days of the week when flight takes place"
      - name: processed_timestamp
        description: "Timestamp indicating when the record was processed"
