version: 2

sources:
  - name: airlabs_api_data
    description: Raw datasets ingested from the AirLabs API.
    meta:
      external_location: "data/{name}.json"
    tables:
      - name: departures_eze
        description: Dataset containing departures data from EZE airport.
