version: 2

models:
  - name: airlines

    data_tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 1
      - dbt_expectations.expect_table_column_count_to_equal:
          value: 3

    columns:
      - name: iata_code
        description: "IATA code of the airline"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_be_unique
          - dbt_expectations.expect_column_value_lengths_to_be_between:
              min_value: 2
              max_value: 3

      - name: name
        description: "Name of the airline"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          - dbt_expectations.expect_column_values_to_not_be_null

      - name: processed_timestamp
        description: "UTC timestamp indicating when the record was processed"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp with time zone
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_row_values_to_have_recent_data:
              datepart: day
              interval: 1

unit_tests:
  - name: test_airlines
    description: "Verify the logic of the airlines model"
    model: airlines
    given:
      - input: source('raw', 'airlines')
        rows:
          - {iata_code: "AR", name: "Aerolineas Argentinas", _dlt_load_id: "1744372569.2028034"}
          - {iata_code: "LH", name: "Lufthansa", _dlt_load_id: "1744372569.2028034"}
          - {iata_code: "LH", name: "System Lufthansa", _dlt_load_id: "1744372569.2028034"}
          - {iata_code: null, name: "Fake Air", _dlt_load_id: "1744372569.2028034"}
          - {iata_code: "AF", name: "Air France", _dlt_load_id: "1744372415.5011466"}
    expect:
      rows:
          - {iata_code: "AR", name: "Aerolineas Argentinas"}
          - {iata_code: "LH", name: "Lufthansa"}
