version: 2

models:
  - name: airports_curated

    data_tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 1
      - dbt_expectations.expect_table_column_count_to_equal:
          value: 7

    columns:
      - name: name
        description: "Name of the airport"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          - dbt_expectations.expect_column_values_to_not_be_null

      - name: iata_code
        description: "IATA code of the airport"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          - dbt_expectations.expect_column_value_lengths_to_equal:
              value: 3
              row_condition: "iata_code is not null"

      - name: icao_code
        description: "ICAO code of the airport"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          - dbt_expectations.expect_column_value_lengths_to_equal:
              value: 4
              row_condition: "icao_code is not null"

      - name: latitude
        description: "Latitude of the location of the airport"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double
          - dbt_expectations.expect_column_values_to_not_be_null

      - name: longitude
        description: "Longitude of the location of the airport"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double
          - dbt_expectations.expect_column_values_to_not_be_null

      - name: country_code
        description: "Code of the country of the airport"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_value_lengths_to_equal:
              value: 2

      - name: processed_timestamp
        description: "Timestamp indicating when the record was processed"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp with time zone
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_row_values_to_have_recent_data:
              datepart: day
              interval: 1
