version: 2

sources:
  - name: airlabs_api_data
    description: Raw datasets ingested from the AirLabs API.
    meta:
      external_location: "data/source/{name}.json"
    tables:
      - name: routes
        description: Dataset containing routes data.
      - name: airlines
        description: Dataset containing airlines data.
      - name: airports
        description: Dataset containing airports data.
      - name: taxes
        description: Dataset containing taxes data.
