version: 2

models:
  - name: airlines_curated

    data_tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 1
      - dbt_expectations.expect_table_column_count_to_equal:
          value: 3

    columns:
      - name: iata_code
        description: "IATA code of the airline"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          - dbt_expectations.expect_column_values_to_be_unique
          - dbt_expectations.expect_column_value_lengths_to_be_between:
              min_value: 2
              max_value: 3

      - name: name
        description: "Name of the airline"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          - dbt_expectations.expect_column_values_to_not_be_null

      - name: processed_timestamp
        description: "Timestamp indicating when the record was processed"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp with time zone
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_row_values_to_have_recent_data:
              datepart: day
              interval: 1
