version: 2

models:
  - name: airlines_curated

    data_tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 1
      - dbt_expectations.expect_table_column_count_to_equal:
          value: 4
      - dbt_expectations.expect_column_pair_values_A_to_be_greater_than_B:
          column_A: updated_timestamp
          column_B: created_timestamp
          or_equal: True

    columns:
      - name: iata_code
        description: "IATA code of the airline"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          - dbt_expectations.expect_column_values_to_be_unique
          - dbt_expectations.expect_column_value_lengths_to_be_between:
              min_value: 2
              max_value: 3

      - name: name
        description: "Name of the airline"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
          - dbt_expectations.expect_column_values_to_not_be_null

      - name: created_timestamp
        description: "Timestamp indicating when the record was created"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp with time zone
          - dbt_expectations.expect_column_values_to_not_be_null

      - name: updated_timestamp
        description: "Timestamp indicating when the record was last updated"
        data_tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp with time zone
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_row_values_to_have_recent_data:
              datepart: day
              interval: 1
