version: 2

sources:
  - name: raw
    description: Raw datasets ingested from the AirLabs API.
    tables:
      - name: airlines
        description: Dataset containing airlines data.
      - name: airports
        description: Dataset containing airports data.
      - name: flight_positions
        description: Dataset containing flight positions data (events).
