name: CI/CD

on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  ENV: dev

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      working-directory: ./dbt
      run: sudo make deps && make dbt-deps

    - name: Run linter
      working-directory: ./dbt
      run: make lint

    - name: Run dbt models
      working-directory: ./dbt
      run: make dbt-run

    - name: Run dbt data tests
      working-directory: ./dbt
      run: make dbt-test-data
